version: '3.8'
services:
  db:
    image: postgres:15.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./init.docker.sql:/docker-entrypoint-initdb.d/01_create_tables.sql